drop table pays if exists;
drop table paysfrancais if exists;
CREATE TABLE IF NOT EXISTS pays (
  ID bigint generated by default as identity,
  code int NOT NULL,
  alpha2 varchar(2) NOT NULL,
  alpha3 varchar(3) NOT NULL,
  nom_en_gb varchar(45) NOT NULL,
  nom_fr_fr varchar(45) NOT NULL,
  PRIMARY KEY (id)
);
commit;
CREATE TABLE IF NOT EXISTS paysfrancais (
 ID bigint generated by default as identity,
 nom_fr_fr varchar(45) NOT NULL,
 PRIMARY KEY (id)
);
commit;